conf/bblayers.conf
setup-environment-internal

Make sure that the build is done in a subfolder, to allow multiple builds from the same workspace.

setup env improvements

---

conf/bblayers.conf
default.xml

Change-Id: Ic15183a0091541c164c9a713818a9b5a6a1447da

default.xml: add meta-backports

---

conf/bblayers.conf
default.xml
setup-environment-internal

Taking the feedback from my previous pull request into account I have created this new pull request. I have broken out each step into individual commits so you can cherry-pick if there are some you want and others you don't.

directory reorganization

---

conf/bblayers.conf

Signed-off-by: Koen Kooi <koen.kooi@linaro.org>

bblayers.conf: add meta-optee layer

---

conf/bblayers.conf

LAYER_CONF_VERSION was updated in commit
10fd24271e771ed12e36edcff0007caa1a4e67e4 in oe-core.
Change-Id: I9dc19698b0533e36d7e92e9d6d518f6c9fe51a17

bblayers.conf: update LCONF_VERSION

---

setup-environment-internal

Change-Id: Ia9851b5ee2e6a44ccade01e504b1c0d363011610
Signed-off-by: Zoltan Kuscsik <zoltan.kuscsik@linaro.org>

setup-environment-internal: fix weston image name

---

setup-environment-internal

This shell script is intended to be used with bash.
Fix the shell script interpreter as appropriate.
Take the opportunity to fix also various shell issues.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

setup-environment-internal: fix shell script shebang

---

default.xml

Signed-off-by: Koen Kooi <koen.kooi@linaro.org>

default.xml: lock meta-96boards to release branch

---

conf/bblayers.conf
default.xml

Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>

default.xml: add meta-ti

---

default.xml

Change-Id: Ic21672e74f372974bd95f84c6d08704a56dc985a

default.xml: use morty branch for meta-qcom

---

default.xml

Update the revisions of the remaining layers without rocko branch.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

default.xml: switch meta-virtualization to rocko branch

---

conf/bblayers.conf
default.xml

from meta-browser:
b5fa3f598236 (Add dependency on meta-rust)
e.g.
https://github.com/OSSystems/meta-browser/commit/b5fa3f598236a58da6217852340f5f8dd01c9a71
Change-Id: I6fd29819c7f05974a99b1875db86bc062a78e5fe

add dependency on meta-rust, needed by meta-browser

---

conf/bblayers.conf
default.xml

Signed-off-by: vishal <vishal.bhoj@linaro.org>

Include meta-updater repository

---

conf/bblayers.conf
default.xml

https://ci.linaro.org/job/lt-qcom-openembedded-rpb-warrior/53/DISTRO=rpb,MACHINE=dragonboard-410c,label=docker-stretch-amd64/console

 Add meta-clang layer now meta-browser depends on it

---

conf/bblayers.conf
default.xml

https://ci.linaro.org/job/lt-qcom-openembedded-rpb-thud/178/DISTRO=rpb,MACHINE=dragonboard-410c,label=docker-stretch-amd64/console

Add meta-clang layer now meta-browser depends on it

---

README.md
conf/bblayers.conf
default.xml

Add dependency on meta-selinux so build works. Also add meta-freescale layer. Can this be also cherry-picked to warrior?

rpb master fixes

---

conf/bblayers.conf

conf/bblayers.conf: Add meta-backports

---

default.xml

default.xml: Change meta-browser to use zeus branch

---

default.xml

default.xml: Change meta-browser to use warrior branch

---

default.xml

default.xml: Change meta-browser to use thud branch

---

README.md
conf/bblayers.conf
default.xml

Signed-off-by: Sumit Garg <sumit.garg@linaro.org>

Switch RPB builds to use meta-arm-toolchain layer

---

default.xml

default.xml: Use dunfell branch for meta-clang

---

setup-environment-internal

We build generic test images for qemuarm regularly.

setup-environment-internal: add qemu Arm platforms

---

sa8155p-adp/21.12.xml

Signed-off-by: Bhupesh Sharma <bhupesh.sharma@linaro.org>

sa8155p-adp: add 21.12 release

---

.github/workflows/build-template.yml

We see errors with tuxsuite 1.0.3 version. Pinning to previous working release until the issue is fixed
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>

Pin tuxsuite version

---

.github/workflows/build-template.yml

This reverts commit 46cef83858da6b8b70f9ae0626bb33898de601f5.

Revert "Pin tuxsuite version"

---

conf/bblayers.conf
default.xml

manifest: remove meta-python2 

---

.github/workflows/daily.yml

Test master branch in addition to qcom/* branches.

.github: test master too

---

conf/bblayers.conf
default.xml

Drop meta-96boards and meta-arm/arm-toolchain from `qcom/master` manifest and bblayers.conf

Drop unused layers
