96boards/oe-rpb-manifest

default.xml
the manifest is supposed to track the 'stable' branch of OE layers. We only want
to use master for a selected number of layers.
Change-Id: I2c5b2021b22459de61e66ace98ae1c68c195edc2
=> default.xml: default to jethro branch and use master selectively

setup-environment-internal
Some BSP might need EULA to be accepted, such as for example the BSP from
meta-qcom. This is a generic implementation of the EULA mechanism. If a BSP
needs a EULA, it needs to provide the EULA text file as conf/EULA/$MACHINE. In
which case the text will be presented to the user, who can decide to accept it
or not.
When accepted, the variable ACCEPT_EULA_$MACHINE is set to '1' in auto.conf, and
it can be used by the BSP layer.
For automation and CI, it is possible to preset the value of
ACCEPT_EULA_$MACHINE, by setting EULA_$MACHINE in the environment, before
calling setup-environment scripts.
Change-Id: I9fead8a8390bdee20d56cb3d22fa2ba3f42f2371
=> setup-environment-internal: add support for BSP's EULA

setup-environment-internal
The logic we used to detec whether a EULA is needed or not relies on:
find ../sources -print | grep "conf/eula/$MACHINE"
However, when there is no EULA for a specific MACHINE, grep will return
an error code, and if setup-environment script is called with 'set -e', then it
will fail/abort, which is unexpected. We need this specific command to always
return 0, whether the EULA exists or not, this is what this commit is about.
Change-Id: I2520db42d6232ff12eee841b1ef1bf71fe210443
=> setup-environment-internal: do not fait when EULA is not used

setup-environment-internal
this line is a left over from a4fa50ac636a8982660d856c9a6a2f652c789cf1, and it
should have been removed in this commit.
Change-Id: I18abf19365ccc1c59644bef72bd692f2f0467fb8
=> setup-environment-internal: remove unused line

setup-environment-internal
When the script gives suggestions for what images to build, add in the RPB
images too.
=> setup-environment-internal: list RPB images

setup-environment-internal
Fix the phrasing of the EULA-read message.
=> setup-environment-internal: phrasing

setup-environment-internal
Several shell variables are leaked out to the user's shell when this script is
sourced. This patch cleans them up. 'BUILDDIR' is purposefully leaked because
it is used by 'devtool', for example.
=> setup-environment-internal: cleanup variables

default.xml
meta-backport is not needed for 'master' branch builds, and it is confusing to
have it.
Change-Id: I2f12a934a448c9a2f3ce4d0b8c4ed70d2b129b71
=> default: remove meta-backport

default.xml
It lacks a 'krogoth' branch, which confuses 'repo sync'. Apart from that we shouldn't track master branches from repos outside our control in a 'krogoth' release setup.
Change-Id: I1e5662a498deb406ef59aa1e3bff4d87f84c37eb
Signed-off-by: Koen Kooi <koen.kooi@linaro.org>
=> default.xml: lock meta-browser to a specific SRCREV

setup-environment-internal
Commit a6f29ed was a bit more too aggressive.. and adding quotes when calling
whiptail or dialog was wrong. These tools expect parameters to be passed by
tupple, and adding the quotes does not work. Since this commit, sourcing the
script with MACHINE and/or DISTRO not set would result in bad things such as:
MACHINE = Box options:
--msgbox <text> <height> <width>
--yesno  <text> <height> <width>
--infobox <text> <height> <width>
--inputbox <text> <height> <width> [init]
--passwordbox <text> <height> <width> [init]
--textbox <file> <height> <width>
--menu <text> <height> <width> <listheight> [tag item] ...
--checklist <text> <height> <width> <listheight> [tag item status]...
--radiolist <text> <height> <width> <listheight> [tag item status]...
--gauge <text> <height> <width> <percent> …
=> setup-environment-internal: fix whiptail and dialog command usage

setup-environment-internal
the init script internally calls "repo start work --all" in order to create
a default branch for all repos. However this is confusing for users, since this
is done 'silently' and might in turn checkout a branch without the user being
aware.
It seems that a better approach is to let the users manage their branches as
they want or prefer.
One noticeable change after this patch, is that layer will now be in a
'detached' state, and not in a git branch.
Change-Id: I673b34e3897e6b3cebeb384b19324827595dec92
=> setup-environment-internal: remove 'repo start work'

conf/local.conf
Using PRSERV is a good idea *if* we are building an official distro and its
associated feed. It requires to save/restrore the PRSERV state to make sure we
don't break the versioning. It is not really a good idea to enable it by default
for everyone, since it can cause package numbers to go backwards.
Change-Id: I6cb10a6fb885d45b3b1b1e5bc193f52c9285239f
=> local.conf: do not enable PRSERV by default

conf/bblayers.conf
Add support for ST's Cannes SoC based B2260 96board.
Signed-off-by: Lee Jones <lee.jones@linaro.org>
=> bblayers.conf: add meta-st-cannes layer to BSPLAYERS

README.md
This trivial typo fix is based on master but worth applying also to current default branch krogoth
=> README: fix misspelled link

conf/bblayers.conf
This reverts commit 3bcd667c7b1f4897b54e9224e438a8793dff526e. The
meta-st-cannes2 layer is still not publicly available, we should merge this
change only once the layer exists, otherwise it breaks the build for every
user.
Change-Id: I2375b34978ce5723433790bb17c87f481878adf4
=> Revert "bblayers.conf: add meta-st-cannes layer to BSPLAYERS"

setup-environment, setup-environment-internal
Install a trap handler to cleanup all defined objects, even in the case of an
early return due to error.
=> setup-environment-internal: use a cleanup trap

README.md
The master branch of meta-rpb (currently) has two distros: "rpb" and
"rpb-wayland". Change "rpb-x11" references to "rpb".
=> README.md: fix RPB distro name

setup-environment-internal
Add helper command for building images for mixed 32bit/64bit
ARM builds. The command allows to specify a secondary MACHINE
and image that will be built next to the primary target.
If no secondary image is specified the rpb-minimal image
will be built.
Change-Id: If7e7d45d66c4f5a76e1d471d4e7b3015821dc1e9
Signed-off-by: Zoltan Kuscsik <zoltan.kuscsik@linaro.org>
=> setup: Add helper command to build multiple images

setup-environment-internal
At certain conditions setup-environment-internal exited
earlier than bitbake_secondary_image got defined. This change
fixes the issue by moving the location of function definition.
Change-Id: I13f516bc32c621694bcd6053ea6f32b82719550b
Signed-off-by: Zoltan Kuscsik <kuscsik@gmail.com>
=> setup-environment-internal: move secondar bitbake call location

conf/bblayers.conf, default.xml
Now that we have pushed the meta-st-cannes2 layer publicly, let's link to it.
=> [GIT PULL v2] B2260

setup-environment-internal
The current 'find' command was confused because we have dragonboard410c and
dragonboard410c-32 now, and it would pick both. Instead of using grep to filter,
rely on find -path.
Change-Id: Ie1f9dec542c7d37aca7875b7ad07f01522293e5a
=> setup-environment: fix issue when several machine start with same name

conf/bblayers.conf, default.xml
Now that we have pushed the meta-st-cannes2 layer publicly, let's link to it.
=> [GIT PULL] B2260 for Krogoth

setup-environment-internal
the behavior of sort is different based on the LANG setting, so let's hardcode
it to make sure that we have a consistent output for all users. Using LANG=C
produces a slightly (subjectively) better output in our case that UTF output, e.g.
LANG=C
rpb(meta-rpb)
rpb-eglfs(meta-rpb)
rpb-wayland(meta-rpb)
LANG=en_US.UTF-8
rpb-eglfs(meta-rpb)
rpb(meta-rpb)
rpb-wayland(meta-rpb)
Change-Id: I0501157a1aef71c968960da42b3818a692dd17f2
=> setup-environment: set LANG when using sort to ensure consistent output

README.md
With the '$' sign on each command line , it makes it inconvenient to copy/paste
from the web into a terminal. Since commands are already using the proper markup
tags, they are properly highlighted on the web page, so removing the '$' sign
doesn't make a bad visual impact and let users copy/paste more conveniently.
Change-Id: Id48af8f3b91e9464cd1d3e29b343b97340f0f7b1
=> README.md: remove leading '$'

conf/bblayers.conf, default.xml
It's required for docker recipe.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
=> default.xml: add meta-virtualization layer

conf/local.conf, setup-environment-internal
Since auto.conf is controlled by the user, add rm_work by default
there and allow the user to easily disable if not needed/wanted.
Note that rm_work is currently defined by the rpb distro itself.
Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>
=> setup-environment-internal: enable rm_work by default via auto.conf

conf/bblayers.conf
This layer no longer contains anything needed/useful for OE RPB.
=> bblayers.conf: remove meta-aarch64 from BBLAYERS

conf/local.conf
meta-intel layer ships gstreamer-vaapi-1.0_1.8.2.bb
meta-backports layer ships gstreamer1.0-vaapi_1.10.4.bb
It's causing a build failure:
| configure: error: Requested 'gstreamer-codecparsers-1.0 <= 1.8.99' but
version of GStreamer codec parsers is 1.10.4
Mask the meta-intel recipe, in favor of meta-backports recipe.
Suggested-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
=> local.conf: mask gstreamer-vaapi-1.0_1.8.2.bb from meta-intel

default.xml
Re-order default.xml so it matches the output from 'repo manifest -o' in
a sync'd workspace.
This allows pinned manifests to be compared more easily.
Note, 'repo manifest -o' introduces spaces on blank lines. I left these
in to stick to the exact repo output.
Signed-off-by: Ryan Harkin <ryan.harkin@linaro.org>
=> default.xml: reorder to match 'repo manifest -o'

conf/bblayers.conf
The meta-ruby layer was removed from meta-openembedded [1] because
now is part of oe-core [2].
[1]
http://git.openembedded.org/meta-openembedded/commit/?id=6e7c9636d2
[2]
http://git.openembedded.org/openembedded-core/commit/?id=10fd3b4144
=> conf/bblayers.conf: Remove meta-ruby from meta-openembedded

conf/bblayers.conf, default.xml
This layer will enable stuff built with Clang, such as the BPF
selftests.
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
=> default.xml: add meta-clang layer

default.xml
meta-ti layer has rocko branch now.
It is using linux kernel 4.14, and ti-u-boot-2018.01 branch for u-boot.
If it matters, am57xx-evm.dtb is not available in ti-u-boot-2018.01: am57xx-beagle-x15.dtb + DT overlays are used for am57xx-evm instead.
=> default.xml: meta-ti: rocko branch created

conf/bblayers.conf, default.xml
This enables the following machines:
intel-core2-32
intel-corei7-64
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
=> default.xml: Add meta-intel

default.xml
Cleaned up with:
repo manifest > default.xml
As we want to stick to the same 'order' as much as possible.
=> default.xml: cleanup default with 'repo manifest'

default.xml
Currently, the master branch includes Clang 8.0, which fails to build [1]. While on Thud, let's use the Thud branch.
[1] https://github.com/kraj/meta-clang/issues/106
=> meta-clang: Use Thud branch instead of master

setup-environment-internal
fix misspelled 'environment' in welcome text.
=> setup-environment-internal: spelling

default.xml
In upstream thud and warrior support on master was removed.
https://github.com/kraj/meta-clang/commit/df21a7d3f29cb49783ff93a9f5ba947832a09e25
=> default.xml: Use meta-clang warrior branch

default.xml
The default manifest no longer builds due to changes in meta-rpb that replace
distro_features_check with features_check - a function that doesn't exist in
zeus.
This happens since meta-rpb commit:
65b2829  2019-12-02  Merge pull request #233 from alimon/master
Signed-off-by: Ryan Harkin <ryan.harkin@linaro.org>
=> default: switch meta-rpb to zeus

README.md, conf/bblayers.conf, default.xml
Some layers like meta-rpb (packagegroups) and meta-browser still
depends on Python 2.x.
=> Add meta-python2 layer

conf/bblayers.conf, default.xml
meta-browser doesn't have a zeus branch and master now
has changes which cause parse errors on zeus.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> meta-browser: remove layer from zeus build

default.xml
Recently LAYERCOMPAT was bump to dunfell in master so isn't compatible.
=> default.xml: Use meta-linaro zeus branch

conf/bblayers.conf
All master builds are now failing due to meta-ti dependency on meta-arm. So add the layer
https://ci.linaro.org/view/reference-platform/job/rpb-openembedded-master/1331/DISTRO=rpb-wayland,MACHINE=imx8mqevk,label=docker-stretch-amd64/console
=> Fix rpb master CI failures with meta-ti dependency on meta-arm

default.xml
To fix ci zeus failures, as meta-ti master is now dependent
on meta-arm layer.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> default.xml: meta-ti use Zeus branch

default.xml
With fb15056ff4431 ("libselinux-python: inherit python3targetconfig")
meta-selinux layer broke compatibility with dunfell's oe-core. Fix
meta-selinux to the revision previous to breakage.
Change-Id: Id1f2c1bf2ab6c9b74a14ef65f4de3f8bd135a833
=> default.xml: fix meta-selinux revision for dunfell

conf/bblayers.conf
The meta-browser layer splits into two layers meta-chromium and
meta-firefox.
https://github.com/OSSystems/meta-browser/commit/1cf4e02d7107c50c58061f77015c498d8ee09259
(cherry picked from commit 82812c440846e5a23f6ae52fa5431c3846ba8f9d)
=> conf/bblayers.conf: Update to include meta-chromium

conf/local.conf
Use new overrides style instead of the old one to become compatible with
hanister. Note, this breaks compatibility with older OE branches.
=> local.conf: switch to new style of overrides

conf/bblayers.conf, default.xml
At this moment we are facing an issue with android-tools that
is present on meta-oe and meta-clang/dynamic-layers:
ERROR: Multiple versions of android-tools-conf-configfs are due to be built (/home/builds/oe-rpb-master/build-410c-2/conf/../../layers/meta-openembedded/meta-oe/recipes-devtools/android-tools/android-tools-conf-configfs_1.0.bb
/home/builds/oe-rpb-master/build-410c-2/conf/../../l,ayers/meta-clang/dynamic-layers/selinux/android-tools/android-tools-conf-configfs_1.0.bb). Only one version of a given PN should be built in any given build. You likely need to set PREFERRED_VERSION_android-tools-conf-configfs to select the correct version or don't depend on multiple versions.
After trying to set PREFERRED_VERSION not works due to:
- The dynamic-layers is load after frist parse so a …
=> Remove meta-selinux from the layers to be included for now

conf/bblayers.conf
The meta-ti layer is till not updated to support honister branch.
Disable it for now to unbreak master branch builds.
=> conf/bblayers.conf: disable meta-ti temporarily

default.xml
With the commit e21c11b4a444 ("meta-ti: convert to new override syntax
in honister"), the master branch of meta-ti stopped declaring
compatibility with dunfell. Rather than fixing the revision to
f56051c9a8cf ("ti-rtos-firmware: Update PATH to include ti-sci-fw"), the
latest commit from master branch which is still compatible with dunfell,
switch the meta-ti repo to the dunfell (default) branch.
Change-Id: Id41bc0e76f524fc5725cdb2661a5239002ae9f7a
=> default.xml: fix meta-ti revision to dunfell

conf/bblayers.conf
Since meta-ti has gained compatibility with the honister override
syntax, restore it in the bblayers.conf
=> conf/bblayers.conf: restore meta-ti

conf/bblayers.conf
The meta-ti layer got moved into it's own subdir 'meta-ti-bsp'. Follow
this change in the bblayers.conf
=> bblayer.conf: follow meta-ti changes

default.xml
The meta-browser repo doens't have (yet) the kirkstone branch. Use
master for now.
=> default.xml: use master branch for meta-browser

conf/local.conf
Enable hash equivalence to speed up repetitive builds. This mechanism
detects build tasks that have the same output even though the input
signatures (hash) differ and skips rebuilding tasks depending on the
detected ones.
=> local.conf: enable hash equivalence

conf/bblayers.conf, default.xml
The meta-linaro collection of layers was not receiving significant updates for the last two years. It has been getting odd fixes since May 2020, mostly when one of the layers broke building of RPB. The meta-linaro-toolchain was replaced by meta-arm-toolchain. I think it is time to drop it completely from the RPB manifest.
(cherry picked from commit 0e2bf89f6f2d8c856e1d631571571cb8ed7ee957)
=> default.xml: drop meta-linaro

.github/workflows/daily.yml
This reverts commit 14c610fd3367db4fc621249ac477eb30887c0d9d. Reenable qcom/kirkstone build to make sure that it works properly.
Closes #171
=> Revert ".github: remove kirkstone from daily build"

.github/workflows/build-template.yml
We are going to phase out the individual machine configurations. Stop building them in the CI.
=> CI: stop building for dragonboards / RB5

default.xml
The master version of meta-rust repo has droppped support for dunell. Stick to the 'dunfell' branch, which contains the last commit before dropping dunfell support.
Change-Id: I529eed5770539a679dc4ea563064f71e649982dd
=> default.xml: drop revision for meta-rust

.github/workflows/build-template.yml
In our cloud builds sometimes the default connectivity check URL (yoctoproject.org) returns an error. Point it to google.com to make sure that the connectivity check errors are not caused by some yoctoproject.org misconfiguration (or DoS protection).
=> CI: point to google.com for connectivity check

README.md
The current example gives an invalid MACHINE. meta-qcom has moved to more generic MACHINE types instead of specific board targets.
Give the example most users would be interested in qcom-armv8a.
=> README.md: Update example to reflect current MACHINE names

README.md, default.xml
Point default.xml to the yocoto project.
Once done this repo is still good to produce a useful image.
Also update the example so that MACHINE is valid again.
=> Update oe-rpb-manifest to latest meta-qcom changes

.github/workflows/build-template.yml
Bump actions/setup-python to v5 as pointed out by GH Node.js warning.
=> CI: bump actions/setup-python to v5

default.xml
The master branch of meta-browser has dropped compatibility with dunfell. Switch to the dunfell branch.
=> default.xml: pin meta-browser layer

default.xml
The master branch of meta-browser broke compatibility with the Kirkstone OE release branch, see the ticket at
https://github.com/OSSystems/meta-browser/issues/789. Lock the revision until the compatibility issue is resolved.
=> manifest: lock meta-browser revision to unbreak build

conf/bblayers.conf, default.xml
The QT5 layers becomes outdated, it wasn't updated for the WORKDIR ->
UNPACKDIR changes. Other layers don't depend on the QT5, drop it from builds.
=> Drop qt5 layer

conf/bblayers.conf, default.xml
The QT5 layers becomes outdated, it wasn't updated for the WORKDIR -> UNPACKDIR changes. There are no external dependencies on the qt5 layer. Let's drop it from manifest and from layers.conf
=> Remove meta-qt5 layer

default.xml
With meta-rpb and meta-qcom layers being ready to drop compatibility with scarthgap release, switch to the scarthgap branches.
=> default.xml: switch to scarthgap branches of meta-rpb and meta-qcom
